package com.myproject.monthly_allowance_ma;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agent_Data_Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ตำแหน่งตัวแทน")
	private String agent_position;
	@org.kie.api.definition.type.Label("ตัวแทนที่กลับมา")
	private java.lang.String agent_rejoin;
	@org.kie.api.definition.type.Label("วันที่นัดหมาย")
	private java.util.Date appointment_date;
	@org.kie.api.definition.type.Label("ค่าคอมมิชชั่น")
	private int commission;
	@org.kie.api.definition.type.Label("อายุงาน")
	private int work_month;
	@org.kie.api.definition.type.Label("ใบอนุญาต")
	private String license;
	@org.kie.api.definition.type.Label("ตัวแทนการผลิต")
	private java.lang.String production_agent;
	@org.kie.api.definition.type.Label("ตัวแทนบริการ")
	private java.lang.String servicing_agent;

	@org.kie.api.definition.type.Label("ข้อมูลตัวแทน")
	private java.lang.String agent;

	@org.kie.api.definition.type.Label("ผ่านการอบรมหลักสูตรที่ปริษัทกำหนด")
	private java.lang.Boolean training;

	@org.kie.api.definition.type.Label("อัตราการผ่านกิจกรรม")
	private int join_activities;

	@org.kie.api.definition.type.Label("การบันทึกผลงาน")
	private int daily_activities;

	@org.kie.api.definition.type.Label("หมายเลขกรมธรรม์")
	private int policy_no;

	@org.kie.api.definition.type.Label("ประเภทของกรมธรรม์")
	private java.lang.String policy_type;

	@org.kie.api.definition.type.Label("ข้อมูล FYC รวมตามรอบผลงาน")
	private java.lang.String total_fyc;

	@org.kie.api.definition.type.Label("FYC อนุมัติใหม่")
	private int new_fyc;

	@org.kie.api.definition.type.Label("Monthly Allowance")
	private int monthly_allowance;

	@org.kie.api.definition.type.Label("error")
	private java.lang.String error;

	@org.kie.api.definition.type.Label("recal")
	private java.lang.String recal;

	@org.kie.api.definition.type.Label("ยอดการคำนวณครั้งก่อน")
	private int old_amount;

	@org.kie.api.definition.type.Label("ยอดการคำนวณครั้งนี้")
	private int new_amount;

	@org.kie.api.definition.type.Label("ยอดสุทธิจากการ Re-calculation")
	private int net_amount;

	public Agent_Data_Object() {
	}

	public java.lang.String getAgent_rejoin() {
		return this.agent_rejoin;
	}

	public void setAgent_rejoin(java.lang.String agent_rejoin) {
		this.agent_rejoin = agent_rejoin;
	}

	public java.util.Date getAppointment_date() {
		return this.appointment_date;
	}

	public void setAppointment_date(java.util.Date appointment_date) {
		this.appointment_date = appointment_date;
	}

	public int getCommission() {
		return this.commission;
	}

	public void setCommission(int commission) {
		this.commission = commission;
	}

	public java.lang.String getProduction_agent() {
		return this.production_agent;
	}

	public void setProduction_agent(java.lang.String production_agent) {
		this.production_agent = production_agent;
	}

	public java.lang.String getServicing_agent() {
		return this.servicing_agent;
	}

	public void setServicing_agent(java.lang.String servicing_agent) {
		this.servicing_agent = servicing_agent;
	}

	public java.lang.String getAgent_position() {
		return this.agent_position;
	}

	public void setAgent_position(java.lang.String agent_position) {
		this.agent_position = agent_position;
	}

	public int getWork_month() {
		return this.work_month;
	}

	public void setWork_month(int work_month) {
		this.work_month = work_month;
	}

	public java.lang.String getAgent() {
		return this.agent;
	}

	public void setAgent(java.lang.String agent) {
		this.agent = agent;
	}

	public java.lang.Boolean getTraining() {
		return this.training;
	}

	public void setTraining(java.lang.Boolean training) {
		this.training = training;
	}

	public int getJoin_activities() {
		return this.join_activities;
	}

	public void setJoin_activities(int join_activities) {
		this.join_activities = join_activities;
	}

	public int getDaily_activities() {
		return this.daily_activities;
	}

	public void setDaily_activities(int daily_activities) {
		this.daily_activities = daily_activities;
	}

	public int getPolicy_no() {
		return this.policy_no;
	}

	public void setPolicy_no(int policy_no) {
		this.policy_no = policy_no;
	}

	public java.lang.String getPolicy_type() {
		return this.policy_type;
	}

	public void setPolicy_type(java.lang.String policy_type) {
		this.policy_type = policy_type;
	}

	public java.lang.String getTotal_fyc() {
		return this.total_fyc;
	}

	public void setTotal_fyc(java.lang.String total_fyc) {
		this.total_fyc = total_fyc;
	}

	public int getNew_fyc() {
		return this.new_fyc;
	}

	public void setNew_fyc(int new_fyc) {
		this.new_fyc = new_fyc;
	}

	public int getMonthly_allowance() {
		return this.monthly_allowance;
	}

	public void setMonthly_allowance(int monthly_allowance) {
		this.monthly_allowance = monthly_allowance;
	}

	public java.lang.String getLicense() {
		return this.license;
	}

	public void setLicense(java.lang.String license) {
		this.license = license;
	}

	public java.lang.String getError() {
		return this.error;
	}

	public void setError(java.lang.String error) {
		this.error = error;
	}

	public java.lang.String getRecal() {
		return this.recal;
	}

	public void setRecal(java.lang.String recal) {
		this.recal = recal;
	}

	public int getOld_amount() {
		return this.old_amount;
	}

	public void setOld_amount(int old_amount) {
		this.old_amount = old_amount;
	}

	public int getNet_amount() {
		return this.net_amount;
	}

	public void setNet_amount(int net_amount) {
		this.net_amount = net_amount;
	}

	public int getNew_amount() {
		return this.new_amount;
	}

	public void setNew_amount(int new_amount) {
		this.new_amount = new_amount;
	}

	public Agent_Data_Object(java.lang.String agent_position,
			java.lang.String agent_rejoin, java.util.Date appointment_date,
			int commission, int work_month, java.lang.String license,
			java.lang.String production_agent,
			java.lang.String servicing_agent, java.lang.String agent,
			java.lang.Boolean training, int join_activities,
			int daily_activities, int policy_no, java.lang.String policy_type,
			java.lang.String total_fyc, int new_fyc, int monthly_allowance,
			java.lang.String error, java.lang.String recal, int old_amount,
			int new_amount, int net_amount) {
		this.agent_position = agent_position;
		this.agent_rejoin = agent_rejoin;
		this.appointment_date = appointment_date;
		this.commission = commission;
		this.work_month = work_month;
		this.license = license;
		this.production_agent = production_agent;
		this.servicing_agent = servicing_agent;
		this.agent = agent;
		this.training = training;
		this.join_activities = join_activities;
		this.daily_activities = daily_activities;
		this.policy_no = policy_no;
		this.policy_type = policy_type;
		this.total_fyc = total_fyc;
		this.new_fyc = new_fyc;
		this.monthly_allowance = monthly_allowance;
		this.error = error;
		this.recal = recal;
		this.old_amount = old_amount;
		this.new_amount = new_amount;
		this.net_amount = net_amount;
	}

}